// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqLw-EB02cj7Csgq4fkaI4PbmmSVAah-c',
    appId: '1:816128299921:web:4288aaa292ceae18058030',
    messagingSenderId: '816128299921',
    projectId: 'fbla-2023-mobile-app',
    authDomain: 'fbla-2023-mobile-app.firebaseapp.com',
    storageBucket: 'fbla-2023-mobile-app.appspot.com',
    measurementId: 'G-GVS0Z3X125',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWOB6oZWbecrwOuD8NKgqOSYTlJXG_Xl4',
    appId: '1:816128299921:android:7499c9bc5ef4ebea058030',
    messagingSenderId: '816128299921',
    projectId: 'fbla-2023-mobile-app',
    storageBucket: 'fbla-2023-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtPhSTG5EpXPeqK2MCP3riTROfc6fqc2w',
    appId: '1:816128299921:ios:fc3ac83f3e54ca7b058030',
    messagingSenderId: '816128299921',
    projectId: 'fbla-2023-mobile-app',
    storageBucket: 'fbla-2023-mobile-app.appspot.com',
    iosClientId: '816128299921-pe46vo9m669062k5415r2bp6fuucu7t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbla2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtPhSTG5EpXPeqK2MCP3riTROfc6fqc2w',
    appId: '1:816128299921:ios:fc3ac83f3e54ca7b058030',
    messagingSenderId: '816128299921',
    projectId: 'fbla-2023-mobile-app',
    storageBucket: 'fbla-2023-mobile-app.appspot.com',
    iosClientId: '816128299921-pe46vo9m669062k5415r2bp6fuucu7t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbla2023',
  );
}
